spring:
  application:
    name: taco-cloud
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    mongodb:
        host: localhost
        port: 27017
        username: test
        password: test
        database: tacoclouddb
